version: "2"

services:
  graphql:
    build: ./graphql
    restart: always
  calendar-export:
    build: ./calendar-export
    environment:
      - URL=http://localhost:8080
      - APP_KEY=12345678901234567890abcdefabcdef
      - PORT=4001
      - GRAPHQL_ENDPOINT=http://graphql:4000
    restart: always
    links:
      - graphql
    ports:
      - 8080:4001
